config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def show; end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.save
    redirect_to articles_path
  end

  def edit; end

  private

  def article_params
    params.require(:article).permit(:title, :content)
  end

  def set_article
    @article = Article.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/index.html.erb
<div class="nav-bar">
    <%= link_to "Wikinimous", articles_path%>
    <%= link_to "New article", new_article_path%>
</div>

<div class="container">
  <div class="articles">
    <% @articles.each do |article| %>
    <div class="article">
      <h2><%= link_to article.title, article_path(article) %></h2>
      <p><%= article.content %></p>
    </div>
    <% end %>
  </div>
</div>

app/views/articles/new.html.erb
<h2>New article</h2>
<%= form_for(@article) do |f| %>
  <%= f.label :Title %>
  <%= f.text_field :title %>
  <%= f.label :Content %>
  <%= f.text_field :content %>
  <%= f.submit "Create article"%>
<% end %>

app/views/articles/show.html.erb
<div class="container">
  <h2><%= @article.title %></h2>
  <p><%= @article.content %></p>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptate praesentium maxime nesciunt iste, unde odit. Aliquid deserunt amet debitis odio nesciunt non, corrupti repellat molestias similique assumenda quia quo corporis!</p>
  <div class="div">

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>